#!/usr/bin/env python3

from farm_blast import pipeline, utils

options = pipeline.get_opts()

if options.fix_coords_in_blast_output:
    utils.fix_blast_coords('blast.out.tmp.gz', 'query.split.coords', 'blast.out.gz')
else:
    blast_pipeline = pipeline.Pipeline(options)
    blast_pipeline.run()
